### ISSUE TITLE
Handle libEGL, libGL and DRI

### ISSUE THREAD

**Issue by probonopd** [VHSgunzo/sharun#1]
Using [userland-execve](https://github.com/io12/userland-execve-rust) is a very interesting approach @VHSgunzo, very clever.

I tried to experiment with sharun a bit, but I am running into an issue:
Some applicatons, e.g., PrusaSlicer, require libGL and DRI for 3D graphics rendering.
It seems like this needs to be handled somehow.

https://github.com/probonopd/PrusaSlicer/blob/efe3df7c9a9a3bd8c2b7bdfa3ec6bb31bb67ab41/.github/workflows/build.yml#L111-L114

This approach is certainly not the way to do it but maybe it can give you a hint at where to look. It seems like libGL and DRI and its dependencies (graphics driver libraries) need to be bundled. Can you get it to work?

**Comment by Samueru-sama** [comment]
`LIBGL_DRIVERS_PATH` [was removed recently](https://github.com/NixOS/nixpkgs/issues/328923)

Also I'm not sure if there is ever a need to copy the `dri` dir, instead you just need libGL* and the `share/glvnd/egl_vendor.d` directory, which sharun will automatically point `__EGL_VENDOR_LIBRARY_DIRS` to it.

This is all it took to have a working opengl with this [desmume appimage](https://github.com/Samueru-sama/DeSmuME-AppImage) for example, and similar for a working vulkan here](https://github.com/Samueru-sama/PPSSPP-AppImage).

I noticed `xvfb-run` isn't working on your script? I think I had this issue with an ubuntu runner as well.

**Comment by probonopd** [comment]
xvfb-run runs for the first but not for the second binary - but then again, maybe I am doing it entirely wrong?

**Comment by probonopd** [comment]
> Also I'm not sure if there is ever a need to copy the dri dir, instead you just need libGL* and the share/glvnd/egl_vendor.d directory, which sharun will automatically point __EGL_VENDOR_LIBRARY_DIRS to it.

If I don't do this, then I get:

```
squashfs-root$ ./AppRun 2>&1

(prusa-slicer:1434): Gtk-CRITICAL **: 02:15:47.231: gtk_window_resize: assertion 'width > 0' failed
[2024-11-22 02:15:47.544278] [0x00007f9b6f50f7c0] [error]   UserAccount: Failed to read token - no datafile found.
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
```

**Comment by Samueru-sama** [comment]
Interesting. 

Looks like dri has to be copied here, I also tested the last artifact that has dri, I noticed that if I set `LIBGL_DRIVERS_PATH` to the AppDir dri I get this error instead: 

`libGL error: MESA-LOADER: failed to open radeonsi: libLLVM-15.so.1: cannot open shared object file` 

which is indeed missing from the AppDir.

Also with the removal of `LIBGL_DRIVERS_PATH` I'm not sure what would need to be done in the future.

**Comment by probonopd** [comment]
Found out so far that the string 

```
MESA-LOADER: failed to open %s: %s (search paths %s, suffix %s)
/usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri```
appears in `./shared/lib/libgbm.so.1.0.0` which has to do with [the Mesa3D project](https://www.mesa3d.org/). 

`\$${ORIGIN}` might be wrong, but I am not sure.

**Comment by Samueru-sama** [comment]
Btw I noticed another thing, the `webkit2gtk-4.0` contains binaries.

Those binaries have to be wrapped around with sharun, otherwise they will try to use the host dynamic linker when ran. 

[Something like this would need to be done for those binaries](https://github.com/Samueru-sama/strawberry-AppImage/blob/main/strawberry-appimage.sh#L61-L68)

**Comment by Samueru-sama** [comment]
This [appimage](https://github.com/probonopd/PrusaSlicer/actions/runs/11963749315) works on my PC. 

However it does not work on ubuntu, I get this error: 

```
(prusa-slicer:8225): GLib-GObject-CRITICAL **: 00:48:51.285: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
[2024-11-22 00:48:51.375700] [0x0000715d5cf547c0] [error]   UserAccount: Failed to read token - no datafile found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/local/share/icons/Papirus-Dark/16x16/actions/image-missing.svg: Unable to load image-loading module: /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /run/host/tmp/samuel/Volatile/squashfs-root/shared/lib/libm.so.6: version `GLIBC_2.38' not found (required by /lib/x86_64-linux-gnu/librsvg-2.so.2) (gdk-pixbuf-error-quark, 5)
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/local/share/icons/Papirus-Dark/16x16/actions/image-missing.svg: Unable to load image-loading module: /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /run/host/tmp/samuel/Volatile/squashfs-root/shared/lib/libm.so.6: version `GLIBC_2.38' not found (required by /lib/x86_64-linux-gnu/librsvg-2.so.2) (gdk-pixbuf-error-quark, 5)
zsh: IOT instruction  ./AppRun
```

This is likely because gdk wasn't deployed, which is odd, I noticed that the app crashes when I continue a confirmation dialog that pops up when launching, very likely the strace mode doesn't catch these libs since they are loaded after the confrimation dialog is closed. 

Try deploying gdk manually anyway, add something like this: 

```
# DEPLOY GDK
echo "Deploying gdk..."
GDK_PATH="$(find /usr/lib -type d -regex ".*/gdk-pixbuf-2.0" -print -quit)"
cp -rv "$GDK_PATH" ./shared/lib
echo "Deploying gdk deps..."
find ./shared/lib/gdk-pixbuf-2.0 -type f -name '*.so*' -exec ldd {} \; \
	| awk -F"[> ]" '{print $4}' | xargs -I {} cp -vn {} ./shared/lib
find ./shared/lib -type f -regex '.*gdk.*loaders.cache' \
	-exec sed -i 's|/.*lib.*/gdk-pixbuf.*/.*/loaders/||g' {} \;
```

**Comment by probonopd** [comment]
Thanks @Samueru-sama. Do you know why rpath is getting patched, I thought patching rpath was no longer necessary thanks to [userland-execve](https://github.com/io12/userland-execve-rust)?

**Comment by Samueru-sama** [comment]
@probonopd just checked your last build and it works on ubuntu latest now, and I had to set `LIBGL_DRIVERS_PATH` to make it work on 20.04. 

Note that you can add extra env variables by creating a [`.env`](https://crates.io/crates/dotenv) file next to sharun and add something like `LIBGL_DRIVERS_PATH=${SHARUN_DIR}/shared/lib/dri`

**Comment by VHSgunzo** [comment]
> Using [userland-execve](https://github.com/io12/userland-execve-rust) is a very interesting approach @VHSgunzo, very clever.

Hi! Thanks! I have not yet looked at the problem that is being discussed here

**Comment by Samueru-sama** [comment]
Most of the issues here were solved already, the only thing is that `LIBGL_DRIVERS_PATH` needed to declared here.

What's left is the other issue with webkitgtk.

**Comment by probonopd** [comment]
When I run my [latest build](https://github.com/probonopd/PrusaSlicer/actions/runs/11987654164) made on Ubuntu on a Fedora target system, then I get

```
[2024-11-23 10:03:19.892117] [0x00007fd8560077c0] [error]   UserAccount: Failed to read token - no datafile found.
libEGL fatal: DRI driver not from this Mesa build ('23.2.1-1ubuntu3.1~22.04.2' vs '23.0.1')
```

So there is more to libGL and DRI than meets the eye...

**Comment by probonopd** [comment]
So, for my personal test case I found solutions for all of the above. But it is a lot of manual work, Is it in the scope of this project to provide automation for this? Thanks.

**Comment by Samueru-sama** [comment]
> So, for my personal test case I found solutions for all of the above. But it is a lot of manual work, Is it in the scope of this project to provide automation for this? Thanks.

Not sure, sharun already sets a lot of env variables.

I recently made an AppImage of [Cromite](https://github.com/pkgforge-dev/Cromite-AppImage) (Chromium fork) with sharun and also needed to deploy `lib/dri` however I didn't need to set `LIBGL_DRIVERS_PATH`, this is likely because I'm using the new mesa that doesn't need it (Now it looks for the dri dirs like any other regular shared library). So I'm not sure if this should be added to sharun given it is deprecated.

**Comment by probonopd** [comment]
> I recently made an AppImage of [Cromite](https://github.com/pkgforge-dev/Cromite-AppImage) (Chromium fork) with sharun and also needed to deploy lib/dri however I didn't need to set LIBGL_DRIVERS_PATH, this is likely because I'm using the new mesa that doesn't need it (Now it looks for the dri libs like any other regular shared library).

Great to know @Samueru-sama. Thanks!

>  So I'm not sure if this should be added to sharun given it is deprecated.

If it is no longer needed with the new versions, then no, we wouldn't imho need to handle this separately.
So should this issue be closed then?

**Comment by VHSgunzo** [comment]
Added LIBGL_DRIVERS_PATH so that it could be packaged on the old mesa too
